"""
Diffy MCP Server — exposes query, retrieve, and review_commits as MCP tools.

Usage (stdio transport, default):
    python mcp_server.py

Install dependencies:
    pip install "diffy-backend[mcp]"
    # or just:  pip install mcp
"""

from mcp.server.fastmcp import FastMCP
from rag_pipeline import get_pipeline
import json

mcp = FastMCP("Diffy")

_MAX_QUESTION_LEN = 2000
_TOP_K_MIN = 1
_TOP_K_MAX = 50
_NUM_COMMITS_MIN = 1
_NUM_COMMITS_MAX = 100


def _validate_question(question: str) -> None:
    if not isinstance(question, str) or not question.strip():
        raise ValueError("question must be a non-empty string")
    if len(question) > _MAX_QUESTION_LEN:
        raise ValueError(f"question too long (max {_MAX_QUESTION_LEN} chars)")


def _validate_top_k(top_k: int) -> None:
    if not isinstance(top_k, int) or not (_TOP_K_MIN <= top_k <= _TOP_K_MAX):
        raise ValueError(f"top_k must be an integer between {_TOP_K_MIN} and {_TOP_K_MAX}")


def _validate_num_commits(num_commits: int) -> None:
    if not isinstance(num_commits, int) or not (_NUM_COMMITS_MIN <= num_commits <= _NUM_COMMITS_MAX):
        raise ValueError(
            f"num_commits must be an integer between {_NUM_COMMITS_MIN} and {_NUM_COMMITS_MAX}"
        )


@mcp.tool()
def query(question: str) -> str:
    """
    Ask a question about the codebase using the git-diff RAG index.

    Returns a natural-language answer generated by the configured LLM,
    grounded in the most relevant diff chunks from the commit history.
    """
    try:
        _validate_question(question)
        pipeline = get_pipeline()
        return pipeline.query(question, stream=False)
    except ValueError as e:
        return f"Error: {e}"
    except Exception as e:
        return f"Error: query failed — {e}"


@mcp.tool()
def retrieve(question: str, top_k: int = 5) -> str:
    """
    Retrieve relevant diff chunks for a question without calling the LLM.

    Returns a JSON array of the top-k diff chunks ranked by hybrid
    TF-IDF + cosine-similarity score.

    Args:
        question: The search query (max 2000 chars).
        top_k:    Number of chunks to return (1–50, default 5).
    """
    try:
        _validate_question(question)
        _validate_top_k(top_k)
        pipeline = get_pipeline()
        results = pipeline.retrieve(question, top_k=top_k)
        return json.dumps(results, indent=2)
    except ValueError as e:
        return json.dumps({"error": str(e)})
    except Exception as e:
        return json.dumps({"error": f"retrieve failed — {e}"})


@mcp.tool()
def review_commits(repo_path: str, num_commits: int = 5) -> str:
    """
    Review recent commits in a repository for potential issues.

    Runs a full AI code review over the last num_commits commits and
    returns a Markdown report.

    Args:
        repo_path:   Absolute path to the local git repository.
        num_commits: Number of commits to review (1–100, default 5).
    """
    try:
        if not isinstance(repo_path, str) or not repo_path.strip():
            raise ValueError("repo_path must be a non-empty string")
        _validate_num_commits(num_commits)
        pipeline = get_pipeline()
        return pipeline.review_commits(repo_path, num_commits=num_commits)
    except ValueError as e:
        return f"Error: {e}"
    except Exception as e:
        return f"Error: review_commits failed — {e}"


if __name__ == "__main__":
    mcp.run()
